name: Deploy App

on:
  pull_request:
    branches:
    - master
  schedule:
  - cron: 0 0 * * *
  push:
    branches:
    - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10.15.1]
        os: [ubuntu-latest]

    steps:
    - name: Checkout to Branch
      uses: actions/checkout@master
    
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node_version }}
        
    - name: Install NPM Packages
      run: npm install

    - name: Run Build
      run: npm run build

    - name: Run Deploy
      uses: actions/aws/cli@master
      with:
        args: s3 sync dist/ s3://$AWS_S3_BUCKET
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
