name: Deploy App

on:
  pull_request:
    branches:
    - master
    - stage
  schedule:
  - cron: 0 0 * * *
  push:
    branches:
    - master
    - develop

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10.15.1]
        os: [ubuntu-latest]

    steps:
    - name: Checkout to Branch
      uses: actions/checkout@master
    
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node_version }}
        
    - name: Install NPM Packages
      run: npm install

    - name: Run Build
      run: npm run build

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - name: Test
        run: ls -alF; ls -alF ../; ls -alF ../../

      - name: Run Deploy
        uses: actions/aws/cli@master
        with:
          args: s3 sync dist/ s3://$AWS_S3_BUCKET
          env:
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          secrets: ["AWS_SECRET_KEY_ID", "AWS_SECRET_ACCESS_KEY"]
