name: Deploy App

on:
  pull_request:
    branches:
    - master
    - stage
  schedule:
  - cron: 0 0 * * *
  push:
    branches:
    - develop

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10.15.1]
        os: [ubuntu-latest]

    steps:
    - name: Checkout to Branch
      uses: actions/checkout@master
    
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node_version }}
        
    - name: Install NPM Packages
      run: npm install

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - name: Init Test
        run: echo Test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build, test]
    
    steps:
      - name: Init Deploy
        run: echo Deploy
