export default <Project.Project[]>[
  {
    id: 1,
    name: 'Seongg.uk',
    organization: null,
    description: 'Published homepage for introducing myself.',
    from: '2019-08-13',
    to: null,
    roles: [
      {
        name: 'Front-End Developer',
        contribution_percentage: 100,
        from: '2019-08-13',
        to: null,
      },
      {
        name: 'Web Designer',
        contribution_percentage: 100,
        from: '2019-08-13',
        to: null,
      },
    ],
    stacks: ['Vue.js', 'TypeScript'],
    images: [],
    status: 'proceeding',
  },
  {
    id: 2,
    name: 'ONDA Hotel Extranet',
    organization: null,
    description: '',
    from: '2017-11',
    to: '2018-12-14',
    roles: [
      {
        name: 'Front-End Developer',
        contribution_percentage: 70,
        from: '2017-11',
        to: '2018-12-14',
      },
      {
        name: 'Back-End Developer',
        contribution_percentage: 40,
        from: '2018-02',
        to: '2018-12-14',
      },
    ],
    stacks: ['Angular', 'TypeScript', 'Rx.js', 'Apollo', 'Node.js', 'GraphQL', 'Sequelize.js', 'MySQL'],
    images: [],
    status: 'leave',
  },
  {
    id: 3,
    name: 'ONDA Plus',
    organization: null,
    description: 'ONDA Pension PMS',
    from: '2018-02-04',
    to: '2018-11',
    roles: [
      {
        name: 'Front-End Developer',
        contribution_percentage: 40,
        from: '2018-02-04',
        to: '2018-11',
      },
      {
        name: 'Back-End Developer',
        contribution_percentage: 30,
        from: '2018-03',
        to: '2018-11',
      },
    ],
    stacks: ['Angular', 'TypeScript', 'Rx.js', 'Apollo', 'Node.js', 'GraphQL', 'Sequelize.js', 'MySQL'],
    images: [],
    status: 'leave',
  },
  {
    id: 4,
    name: 'ONDA Wave',
    organization: null,
    description: 'ONDA B&B/Guest House PMS',
    from: '2019-01-02',
    to: null,
    roles: [
      {
        name: 'Front-End Developer',
        contribution_percentage: 30,
        from: '2019-01-02',
        to: null,
      },
      {
        name: 'Back-End Developer',
        contribution_percentage: 50,
        from: '2019-01-02',
        to: null,
      },
    ],
    stacks: ['Vue.js', 'TypeScript', 'Vuex', 'Node.js', 'Express.js', 'Sequelize.js', 'PostgreSQL'],
    images: [],
    status: 'proceeding',
  },
];
